import os
import sys
from snakemake.utils import min_version

from pathlib import Path

from helper import get_clio_msrc_data, http

###### minimum snakemake version ######
min_version("8.0")

###### storage configuration ######
storage clio:
    provider="fabric",
    username="u369179-sub3"

storage flashnet:
    provider="fabric",
    username="u369179-sub4"

storage http:
    provider="http",

###### rules ######
include: "rules/msrc.smk"
include: "rules/flashnet.smk"

## STARTER BALEEN ##
rule simple_workflow:
  input:
    http(storage, "https://ftp.pdl.cmu.edu/pub/datasets/Baleen24/storage/201910/Region1/full_0.1_0.1.trace"),
  output:
      "data/standardized/simple/full_0.1_0.1.trace",
  shell:
    """
    echo $(basename {input}) > {output}
    """
