#[SETTINGS]
window_len: 60
step_size: 30

# [DATA]
dataset: '1063'
timesplit: '1m'
data_path: '/home/cc/clio/runs/raw/tencent/characteristic/1063/1m/characteristic.csv'
features: ['iops', 'read_write_ratio', 'write_size_ratio', 'bandwidth', 'read_count', 'write_count']
preprocess: 'mean' # 'mean', 'none', 'fft'

# [Model]
ks_drift: True
cvm_drift: True
threshold: 0.005

# [Output]
output_path: './output'
output_mode: 'all' # 'all' or 'rank'
rank_by: 'P_Value' # 'P_Value' or 'Distance'
percentage: 0.3 # 'rank'
save_plot: True
